# Generated by Django 4.2.5 on 2023-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=30)),
                ('gsize', models.IntegerField()),
                ('gtype', models.CharField(max_length=30)),
                ('gstyle', models.CharField(max_length=10)),
                ('gos', models.CharField(max_length=30)),
            ],
        ),
    ]
